### ISSUE TITLE
Send a Google Form

### ISSUE THREAD

**Issue by j-rewerts** [CityofEdmonton/Mailman#162]
Based on a discussion with Danny Edwards.

you know how you can embed a Google Form within an email, to be filled out by users?
would it be possible to have THOSE be included as well as the Google Docs?
that's what we use Mailman for, in the majority of use cases
we use mailman to send a Google Form for something
(we use it too for notifications of stuff, but right now the large portion of it is sending forms to be filled out)
Sign off on app testing
Survey for Post Deployment feedback
Data confirmation for machine and location data

**Comment by j-rewerts** [comment]
I'm thinking this could handle wiring up the prefilled link for Google Forms. When users receive the email, it is simply the prefilled form to fill out. It could also handle any encoding/decoding of the URL.

**Comment by dchenier** [comment]
Fixed in latest release (October 14 2018)
