### ISSUE TITLE
Sending email to users with an apostrophe in their name doesn't work

### ISSUE THREAD

**Issue by dchenier** [CityofEdmonton/Mailman#183]
Reported by Kierstin.  Test case had "O'Connell" in the name

Need to validate by creating a test user.

**Comment by j-rewerts** [comment]
I think I know what she's talking about. The "Who are you sending to?" card has a crazy Reg Exp that doesn't allow '. She [here](https://github.com/coe-google-apps-support/Mailman/blob/a718b19c44514ac40564bf9077f43239ab019eb6/src/client/js/controllers/standard-mail-config.js#L129) for an example.

If you need help deciphering the crazy reg exp, I should be able to give you a hand.

**Comment by j-rewerts** [comment]
In the mean time though, if the person's name is in the Google Sheet, Mailman should still allow sending to that person. It just won't work when you're hard coding their name into the "Who are you sending to?" card.
