### ISSUE TITLE
Rich Text Editor popup is hosted on its own server

### ISSUE THREAD

**Issue by dchenier** [CityofEdmonton/Mailman#192]
I have a confession.

The only way I could get the popup working originally was to place the popup html and it's dependencies on their own server. It's currently hosted by gdev.edmonton.ca, at gdev.edmonton.ca/mailman/tinymce/popup.html

We should investigate putting all of this logic into the MailMan distribution bundle, so that it has no external dependencies.  I do not know if it is possible though.

At the very least the process of deploying the popup is not automated in any way.  It should be included in the gulp file, or in a build server, or something like that.

**Comment by j-rewerts** [comment]
:)
The truth comes out!
