### ISSUE TITLE
Rich Text Editor is not under source control

### ISSUE THREAD

**Issue by dchenier** [CityofEdmonton/Mailman#193]
The Rich Text Editor uses the open source [tinyMCE](https://www.tinymce.com/) control ([LGPL Licensed](https://github.com/tinymce/tinymce/blob/master/LICENSE.TXT)). 

Mailman uses this control and extends it using the [tinyMCE plugin system](https://www.tinymce.com/docs/advanced/creating-a-plugin/).  Originally I had the plugins under the MailMan repo, but the "suggestions" plugin in particular required a lot of references to tinyMCE components.

It ended up being far easier to clone the tinyMCE repo and create the plugins directly in that project. However, I'm not sure how to check this back into github and associate it to MailMan. I think this is a fork..?  @j-rewerts, I need your expertise on this one.

**Comment by j-rewerts** [comment]
So how do we currently import tinyMCE? Using an NPM package?

**Comment by j-rewerts** [comment]
I do a weird sort of local import for jquery [here](https://github.com/coe-google-apps-support/Mailman/blob/88c3ccd47b1920b4bd1e4093b5b6f8186adb277a/package.json#L45). Notice the browserify-shim a little further down. I kind of forget exactly how it works, but I believe the idea is you can add a local, non-CDN version of a package if needed. 

May help with tinyMCE?

**Comment by dchenier** [comment]
tinyMCE is actually imported using an NPM page, but that's loading the official tinyMCE version without the additional custom plugins.  tinyMCE also has the ability to specify a [baseUrl](https://github.com/coe-google-apps-support/Mailman/blob/88c3ccd47b1920b4bd1e4093b5b6f8186adb277a/src/client/js/card/card-textarea.js#L91) in which plugins, etc. get loaded.

But that's not really the problem. I could overcome that easily and the plugins would be just fine in the addon frame.

The problem is more in the popup window, in which I need to load a small amount of HTML, and a relatively large amount of script. It's easy to open the popup with a given URL; much harder to open the window and inject the script.  Child windows don't have the same dependencies loaded as parent windows.

In particular, in the "parent" window (the add on frame), there's the tinymce global javascript object handing off of window.  I need another (or same) object in the child window. Then I need to set up the messaging hooks between the windows.

**Comment by dchenier** [comment]
obsolete
