### ISSUE TITLE
Create new Merge Template list

### ISSUE THREAD

**Issue by j-rewerts** [CityofEdmonton/Mailman#210]

**Comment by dchenier** [comment]
We needs to reproduce the legacy MergeTemplate list.

We need to:

- Read in the merge templates in a sheet from the /api/MergeTemplates/{SheetId} endpoint. This will require the [MergeTemplate.js store](https://github.com/CityofEdmonton/Mailman/blob/mailman-2.0/src/Mailman.Server/ClientApp/src/store/MergeTemplates.js) to be updated.
- The [Home component](https://github.com/CityofEdmonton/Mailman/blob/mailman-2.0/src/Mailman.Server/ClientApp/src/components/Home.js) will need to be updated to display the merge templates
- Routes will have to be added for editing and previewing templates.  New components should be added for these but should not be implemented - just placeholders for future implementation
- Placeholder button is needed to run the template 
- Placeholder button is needed to delete the template
