### ISSUE TITLE
Implment sending emails

### ISSUE THREAD

**Issue by dchenier** [CityofEdmonton/Mailman#242]
https://github.com/CityofEdmonton/Mailman/blob/7c3b1ebb780092f070e64a1e7a295c22d697c859/src/Mailman.Services/Google/GmailServiceImpl.cs#L33

Needs to be implemented.

**Comment by Zhipeng-Chang** [comment]
Hi Dan, I just added the Gmail server into the code, but the service needs the authentication to send the email, at this [line](https://github.com/Zhipeng-Chang/Mailman/blob/aff5d82a07cfcc401ea47e6a640c1c78085993df/src/Mailman.Services/Google/GmailServiceImpl.cs#L50), could you please take a look of this and we could talk about how to pass the token to here

**Comment by dchenier** [comment]
Hey @Zhipeng-Chang,

You should be able to use the service from [this line](https://github.com/Zhipeng-Chang/Mailman/blob/aff5d82a07cfcc401ea47e6a640c1c78085993df/src/Mailman.Services/Google/GmailServiceImpl.cs#L35).  

Basically, there's 3 different ways to get the auth token, so that line takes care of each way and brings the service in.
1. From the security context of the current logged in user
2. From the token passed from the "Main Server" to the worker server
3. Using a static service account for the integration tests.

Also, StringWriter is an IDisposable object, so can you pleas wrap [this line](https://github.com/Zhipeng-Chang/Mailman/blob/aff5d82a07cfcc401ea47e6a640c1c78085993df/src/Mailman.Services/Google/GmailServiceImpl.cs#L42) in a using statement.  i.e.: 
```
Message message;
using (var msgStr = new StringWriter())
{
    msg.Save(msgStr);
    message = new Message {Raw = Base64UrlEncode(msgStr.ToString())}
}
```
